### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by r-go** [klamonte/jexer#25]
--- exec-maven-plugin:1.2.1:exec (default-cli) @ jexer ---
Exception in thread "Thread-6" java.lang.NullPointerException
	at jexer.TApplication.secondaryHandleEvent(TApplication.java:1129)
	at jexer.TApplication.access$800(TApplication.java:72)
	at jexer.TApplication$WidgetEventHandler.run(TApplication.java:381)
	at java.lang.Thread.run(Thread.java:744)

**Comment by klamonte** [comment]
What version of the code?  What application is running?  Is it one of the demos?  What UI action occurred?  Was something being clicked on, dragged, keyboard input, ... ?

**Comment by r-go** [comment]
Apology for not providing more information. So, I just downloaded the head from the master branch and played with the Demo1 application (Was playing with the font size and then with message boxes - if I recall when it crashed). No single line of code was changed. 

I've tried to reproduce it -  to no avail. 

macOS 10.13.2/ NetBeans 8.2/ Jdk 1.8.0

**Comment by r-go** [comment]
Just got another one:  I was playing with the Demo1 - Editor Windows (editing / randomly typing etc)
Can't reproduce it either ...
------------------------------------------------------------------------
Building Jexer 0.0.6
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ jexer ---
Exception in thread "Thread-3" java.lang.IndexOutOfBoundsException: Max length is 33, requested position 33
	at jexer.teditor.Line.setCursor(Line.java:97)
	at jexer.teditor.Document.setCursor(Document.java:188)
	at jexer.TEditorWidget.onMouseDown(TEditorWidget.java:171)
	at jexer.TWidget.onMouseDown(TWidget.java:361)
	at jexer.TWindow.onMouseDown(TWindow.java:428)
	at jexer.TWidget.handleEvent(TWidget.java:511)
	at jexer.TApplication.primaryHandleEvent(TApplication.java:1070)
	at jexer.TApplication.access$700(TApplication.java:72)
	at jexer.TApplication$WidgetEventHandler.run(TApplication.java:379)
	at java.lang.Thread.run(Thread.java:744)

**Comment by klamonte** [comment]
Took some thinking but I think both of those should be fixed now.  Thanks for the followup info!
